In [ ]:
import numpy as np

my_list = [ 1,2,3,4]
x=np.array(my_list)
print(x)

[1 2 3 4]


In [ ]:
# pass in a list of lists to create multi dimentional array
m = np.array( [[7,8,9], [10,11,12]]
)
print(m)

[[ 7  8  9]
 [10 11 12]]


In [ ]:
m.shape

(2, 3)

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped (2x3):\n", reshaped_arr)

Original: [1 2 3 4 5 6]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]


In [ ]:
# create 3x3 matrix
n = np.matrix([[1,2,3],
               [5,6,7],
               [55,66,44]]

)
print(n)
type(n)
print("Main Diagonal = ",np.diag(n))
print("Elements above main Diagonal = ", np.diag(n,1))
print("Elements below main Diagonal = ", np.diag(n,-1))
print("Elements one step below main Diagonal = ", np.diag(n,-2))


[[ 1  2  3]
 [ 5  6  7]
 [55 66 44]]
Main Diagonal =  [ 1  6 44]
Elements above main Diagonal =  [2 7]
Elements below main Diagonal =  [ 5 66]
Elements one step below main Diagonal =  [55]


In [ ]:
# Repeating list
arr = np.array([1,2,3]*3)
print(arr)

# Repeating elements
arr = np.repeat([1,2,3],3)
print(arr)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [ ]:
# Vertical Stack Row wise
p= np.ones([3,3],int)
print(p)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically (creates a 2D array)
v_stacked = np.vstack((a, b))

print(v_stacked)

# Hstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack horizontally
h_stacked_1d = np.hstack((a, b))

print(h_stacked_1d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Doing Add and Sub element wise in array
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2) # power square
print(a@b)  # dot product 1*4 + 2*5 + 3*6 =32

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
32


In [ ]:
# Notice the outer brackets around all three rows
z = np.array([[4, 5, 6],
              [4, 5, 6],
              [4, 5, 6]])

print(len(z))

#shape
print(z.shape)

#transpose
print(z.T)


3
(3, 3)
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [ ]:
# covert int to float type
z = z.astype('f')
print(type(z))
z.dtype


<class 'numpy.ndarray'>


dtype('float32')

In [ ]:
# MATH FUNCTIONS
a=np.array([4,0,2,1,2,3])
print(a.sum())
print(a.min())
print(a.max())
print(round(a.std(),3)) # standard deviation
print(a.argmax())   # index location of max element
print(a.argmin())   # index location of min element

12
0
4
1.291
0
1


In [ ]:
import numpy as np

# Correct function is 'arange' (array range)
s = np.arange(100)

print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
# indexing / slicing

s= np.arange(6)**2  # square 1st 6 elements of s
print(s)
print(s[-2]) #2nd last element

[ 0  1  4  9 16 25]
16


In [ ]:
# print in given range
print(s)
print(s[1:4])  # print from index 1 to 3

s = np.arange(20)

# Syntax: s[start : stop : step]
print(s[0:len(s):2]) # skip 1

[ 0  1  4  9 16 25]
[1 4 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
a = np.arange(100)
print(a)

# Reshape into 10 rows and 10 columns matrix
a = a.reshape(10, 10)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# reshape

a = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2x3
b = a.reshape(2, 3)

print("Reshaped b:\n", b)
print("Original a is unchanged:\n", a)

# resize
a = np.array([1, 2, 3, 4, 5, 6])

# Expand to size 8 (2x4) in-place
a.resize(2, 4)

print("Resized a (in-place with zero padding):\n", a)

Reshaped b:
 [[1 2 3]
 [4 5 6]]
Original a is unchanged:
 [1 2 3 4 5 6]
Resized a (in-place with zero padding):
 [[1 2 3 4]
 [5 6 0 0]]


In [ ]:
b[:3,:-1]

array([[1, 2],
       [4, 5]])