# **1. Constant Array**

In [ ]:
import numpy as np

# Create a 2x2 constant array filled with 7.0
arr = np.full((2, 2), 7.0)
print(arr)

[[7. 7.]
 [7. 7.]]


# **2. Random Values Array**

In [ ]:
import numpy as np

# Create a 2x2 array filled with random floats in range [0.0, 1.0)
rand_arr = np.round(np.random.random((2, 2)), 3)

print(rand_arr)


[[0.362 0.983]
 [0.99  0.726]]


# **3. NumPy Array Properties (10 to 50)**

In [ ]:

arr = np.arange(10, 51)

print("Array: - ", arr)
print("Number of elements:", arr.size)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)

Array: -  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


# **4. Basic Array Creation**

In [ ]:
import numpy as np

# 1D array of 10 zeros
zeros_1d = np.zeros(10)

# 3x3 array containing ones
ones_3x3 = np.ones((3, 3))

# 4x4 identity matrix
identity_4x4 = np.eye(4)

# Step array from 5 to 50 with step size 5
step_arr = np.arange(5, 51, 5)

print("1D Zeros:\n", zeros_1d)
print("\n3x3 Ones:\n", ones_3x3)
print("\n4x4 Identity Matrix:\n", identity_4x4)
print("\nStep Array (5 to 50):\n", step_arr)

1D Zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

3x3 Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Step Array (5 to 50):
 [ 5 10 15 20 25 30 35 40 45 50]


# **5. Reshaping (1 to 24)**

In [ ]:
import numpy as np

arr = np.arange(1, 25)

arr_4x6 = arr.reshape(4, 6)
arr_6x4 = arr.reshape(6, 4)
arr_2x3x4 = arr.reshape(2, 3, 4)

print("4x6 Shape:", arr_4x6.shape, "| Dimensions:", arr_4x6.ndim)
print("6x4 Shape:", arr_6x4.shape, "| Dimensions:", arr_6x4.ndim)
print("2x3x4 Shape:", arr_2x3x4.shape, "| Dimensions:", arr_2x3x4.ndim)

4x6 Shape: (4, 6) | Dimensions: 2
6x4 Shape: (6, 4) | Dimensions: 2
2x3x4 Shape: (2, 3, 4) | Dimensions: 3


# **6. Array Indexing and Slicing**

In [ ]:
import numpy as np

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print("First element:", marks[0])
print("Last element:", marks[-1])
print("Third element:", marks[2])
print("First four elements:", marks[:4])
print("Last three elements:", marks[-3:])

First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


# **7. Element-wise Arithmetic**

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("Square of every element in a:", a ** 2)

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]
Square of every element in a: [ 100  400  900 1600 2500]


# **8. Salary Statistics**

In [ ]:
import numpy as np

salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

print("Total salary:", np.sum(salary))
print("Average salary:", np.mean(salary))
print("Highest salary:", np.max(salary))
print("Lowest salary:", np.min(salary))
print("Median salary:", np.median(salary))
print("Standard deviation:", np.std(salary))

Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard deviation: 8317.902379807063


# **9. Boolean Indexing**

In [ ]:
import numpy as np

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

# Marks greater than 75
print("Marks > 75:", marks[marks > 75])

# Marks between 50 and 80 (inclusive)
print("Marks between 50 and 80:", marks[(marks >= 50) & (marks <= 80)])

# Number of students scoring below 50
print("Number of students scoring below 50:", np.sum(marks < 50))

# Percentage of students who scored 60 or above
pct_60_or_above = (np.sum(marks >= 60) / len(marks)) * 100
print(f"Percentage scoring >= 60: {pct_60_or_above:.1f}%")

Marks > 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students scoring below 50: 3
Percentage scoring >= 60: 60.0%


# **10.  2D-Array Marks Analysis**

In [ ]:
import numpy as np

marks = np.array([
                  [80, 75, 90],
                   [65, 70, 72],
                   [88, 92, 85],
                    [55, 60, 58]
                 ])

tot_per_student = np.sum(marks, axis=1)
avg_per_student = np.mean(marks, axis=1)
avg_per_subject = np.mean(marks, axis=0)
highest_student = np.argmax(tot_per_student) + 1
highest_per_subject = np.max(marks, axis=0)

print("Total marks of each student:", tot_per_student)
print("Average marks of each student:", avg_per_student)
print("Average marks in each subject:", avg_per_subject)
print(f"Student with highest total: Student {highest_student} ({np.max(tot_per_student)} marks)")
print("Highest mark in each subject:", highest_per_subject)

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with highest total: Student 3 (265 marks)
Highest mark in each subject: [88 92 90]


# **11. Matrix Operations & Operator Differences**

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Addition (A + B):\n", A + B)
print("\nElement-wise Multiplication (A * B):\n", A * B)
print("\nMatrix Multiplication (A @ B):\n", A @ B)
print("\nTranspose of A:\n", A.T)

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]


# **12. Daily Temperature Analysis**

In [ ]:
import numpy as np

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

mean_temp = np.mean(temperature)
max_temp = np.max(temperature)
min_temp = np.min(temperature)

print(f"Mean temperature: {mean_temp:.2f}°C")
print(f"Max temperature: {max_temp}°C | Min temperature: {min_temp}°C")
print("Number of days above average temp:", np.sum(temperature > mean_temp))
print("Temperatures > 34°C:", temperature[temperature > 34])
print("Difference (Max - Min):", max_temp - min_temp)
print(f"Standard deviation: {np.std(temperature):.2f}")

Mean temperature: 33.14°C
Max temperature: 37°C | Min temperature: 29°C
Number of days above average temp: 6
Temperatures > 34°C: [35 36 35 37 36]
Difference (Max - Min): 8
Standard deviation: 2.36


# **13. Monthly Sales Determination**

In [ ]:
import numpy as np

sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Total annual sales: ₹", np.sum(sales))
print("Average monthly sales: ₹", np.mean(sales))
print("Month with highest sales: Month", np.argmax(sales) + 1)
print("Month with lowest sales: Month", np.argmin(sales) + 1)
print("Months with sales > ₹20,000:", np.sum(sales > 20000))

# Percentage increase from Jan (index 0) to Dec (index -1)
pct_increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print(f"Percentage increase Jan to Dec: {pct_increase:.2f}%")

Total annual sales: ₹ 240000
Average monthly sales: ₹ 20000.0
Month with highest sales: Month 12
Month with lowest sales: Month 1
Months with sales > ₹20,000: 6
Percentage increase Jan to Dec: 133.33%


# **14. Student Performance Categorization (np.select)**

In [ ]:
import numpy as np

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

tot_marks = np.sum(marks, axis=1)
avg_marks = np.mean(marks, axis=1)
subject_avg = np.mean(marks, axis=0)

print("Total marks per student:", tot_marks)
print("Average per student:", avg_marks)
print("Average mark per subject:", subject_avg)
print("Highest-scoring student: Student", np.argmax(tot_marks) + 1)
print("Lowest-scoring student: Student", np.argmin(tot_marks) + 1)
print("Students with average > 80: Student(s)", np.where(avg_marks > 80)[0] + 1)
print(f"Overall class average: {np.mean(marks):.2f}")

# Assigning performance categories using np.select()
conditions = [
    avg_marks >= 85,
    (avg_marks >= 70) & (avg_marks < 85),
    (avg_marks >= 50) & (avg_marks < 70)
]
choices = ['Excellent', 'Good', 'Average']
performance = np.select(conditions, choices, default='Needs Improvement')

for i, category in enumerate(performance):
    print(f"Student {i+1} Category: {category}")

Total marks per student: [341 275 366 235 316]
Average per student: [85.25 68.75 91.5  58.75 79.  ]
Average mark per subject: [74.  75.6 79.4 77.6]
Highest-scoring student: Student 3
Lowest-scoring student: Student 4
Students with average > 80: Student(s) [1 3]
Overall class average: 76.65
Student 1 Category: Excellent
Student 2 Category: Average
Student 3 Category: Excellent
Student 4 Category: Average
Student 5 Category: Good


# **15 to 19. Random Array Manipulation & Frequency Analysis**

In [ ]:
import numpy as np

# 15. Generate 20 random integers between 1 and 100
arr = np.random.randint(1, 101, size=20)
print("15. Generated Array:\n", arr)

# 16. Find all even numbers
even_nums = arr[arr % 2 == 0]
print("\n16. Even numbers:", even_nums)

# 17. Replace values below 50 with 0
arr_replaced = arr.copy()
arr_replaced[arr_replaced < 50] = 0
print("\n17. Array with values < 50 set to 0:\n", arr_replaced)

# 18. Sort in ascending and descending order
print("\n18. Ascending:", np.sort(arr))
print("18. Descending:", np.sort(arr)[::-1])

# 19. Unique values and frequencies
uniques, counts = np.unique(arr, return_counts=True)
print("\n19. \n Unique values:\n", uniques)
print("Frequencies:\n", counts)

15. Generated Array:
 [30 55 40 45 53  7 12 97  1 43 58 98 96 86 23 52 40 94 69 58]

16. Even numbers: [30 40 12 58 98 96 86 52 40 94 58]

17. Array with values < 50 set to 0:
 [ 0 55  0  0 53  0  0 97  0  0 58 98 96 86  0 52  0 94 69 58]

18. Ascending: [ 1  7 12 23 30 40 40 43 45 52 53 55 58 58 69 86 94 96 97 98]
18. Descending: [98 97 96 94 86 69 58 58 55 53 52 45 43 40 40 30 23 12  7  1]

19. 
 Unique values:
 [ 1  7 12 23 30 40 43 45 52 53 55 58 69 86 94 96 97 98]
Frequencies:
 [1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1]


# **20. 5x5 Matrix Row and Column Means**

In [ ]:
import numpy as np

# Use np.round instead of round() for numpy arrays
mat = np.round(np.random.rand(5, 5), 2)

print("5x5 Matrix:\n", mat)
print("\nRow-wise means:", np.mean(mat, axis=1))
print("Column-wise means:", np.mean(mat, axis=0))


5x5 Matrix:
 [[0.19 0.45 0.6  0.23 0.32]
 [0.46 0.91 0.65 0.02 0.87]
 [0.01 0.34 0.4  0.44 0.01]
 [0.82 0.07 0.4  0.4  0.02]
 [0.07 0.41 0.64 0.5  0.26]]

Row-wise means: [0.358 0.582 0.24  0.342 0.376]
Column-wise means: [0.31  0.436 0.538 0.318 0.296]


# **21. Array Normalization (Min-Max Scaling)**

In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50], dtype=float)

# Min-Max Normalization formula: (X - min) / (max - min)
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))

print("Original Data:", data)
print("Normalized Data:", normalized_data)

Original Data: [10. 20. 30. 40. 50.]
Normalized Data: [0.   0.25 0.5  0.75 1.  ]


# **22. Array Standardization (Z-Score)**

In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50], dtype=float)

# Z-Score Standardization formula: (X - mean) / std
standardized_data = (data - np.mean(data)) / np.std(data)

print("Original Data:", data)
print("Standardized Data:", standardized_data)

Original Data: [10. 20. 30. 40. 50.]
Standardized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


# **23. Exam Marks Score Ranges Distribution**

In [ ]:
import numpy as np

exam_marks = np.random.randint(0, 101, size=100)

range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("Score Ranges Distribution:")
print(f"0–39   : {range_0_39} students")
print(f"40–59  : {range_40_59} students")
print(f"60–79  : {range_60_79} students")
print(f"80–100 : {range_80_100} students")

Score Ranges Distribution:
0–39   : 47 students
40–59  : 23 students
60–79  : 17 students
80–100 : 13 students


# **24. Performance Comparison (Python List vs. NumPy Array)**

In [ ]:
import numpy as np
import time

N = 1_000_000

# Python List Multiplication
list1 = list(range(1, N + 1))
list2 = list(range(1, N + 1))

t0 = time.time()
list_result = [x * y for x, y in zip(list1, list2)]
t1 = time.time()
py_list_time = t1 - t0

# NumPy Array Multiplication
arr1 = np.arange(1, N + 1, dtype=np.int64)
arr2 = np.arange(1, N + 1, dtype=np.int64)

t0 = time.time()
numpy_result = arr1 * arr2
t1 = time.time()
numpy_time = t1 - t0

print(f"Python List Time : {py_list_time:.5f} seconds")
print(f"NumPy Array Time : {numpy_time:.5f} seconds")
print(f"Speedup Factor   : NumPy is {py_list_time / numpy_time:.2f}x faster")

Python List Time : 0.08934 seconds
NumPy Array Time : 0.00309 seconds
Speedup Factor   : NumPy is 28.95x faster
